language: generic

addons:
  apt:
    packages:
      - libssl-dev

matrix:
  include:
    - os: windows

    # osx machines (x86-64)
    - os: osx
      osx_image: xcode12

    - os: osx
      osx_image: xcode11.3

    - os: osx
      osx_image: xcode10.1

    # linux machines (x86-64)
    - os: linux
      dist: Focal

    - os: linux
      dist: Bionic

    - os: linux
      dist: Xenial


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash .ci/install-osx-deps.sh; fi
  - time bash .ci/install-v.sh

install:
  - pwd
  - time make build-release

script:
  - ./vrelease -h
  - ./vrelease -v
