language: generic

_osx_addons: &osx_addons
  addons:
    homebrew:
      packages:
        - openssl
      update: true

_linux_addons: &linux_addons
  addons:
    apt:
      packages:
        - libssl-dev

matrix:
  include:
    - os: windows

    # osx machines (x86-64)
    - os: osx
      osx_image: xcode12
      <<: *osx_addons

    - os: osx
      osx_image: xcode11.3
      <<: *osx_addons

    - os: osx
      osx_image: xcode10.1
      <<: *osx_addons

    # linux machines (x86-64)
    - os: linux
      dist: Focal
      <<: *linux_addons

    - os: linux
      dist: Bionic
      <<: *linux_addons

    - os: linux
      dist: Xenial
      <<: *linux_addons


before_install:
  - time sh .ci/install-v.sh

install:
  - time make build-release

script:
  - ./vrelease -h
  - ./vrelease -v
