language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode12

    - os: osx
      osx_image: xcode11.3

    - os: linux
      dist: Focal

    - os: linux
      dist: Bionic


before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then gem install bundler;  fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ];   then brew install openssl; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libssl-dev; fi

install:
  - time sh .ci/install-v.sh
  - time make build-release

script:
  - ./vrelease -h
  - ./vrelease -v
