name: reusable-tet-routine

inputs:
  artifact:
    required: true
    type: string

  test-file:
    required: true
    type: string

  github-token:
    required: true
    type: string

  committer:
    required: false
    type: string
    default: https://github.com/caian-org/committer/releases/download/v0.4.0/committer

  vrtp:
    required: false
    type: string
    default: vrelease/vrtp

  git-email:
    required: false
    type: string
    default: hi@caian.org

  git-name:
    required: false
    type: string
    default: Caian Ertl

  retrieve-artifact:
    required: false
    type: boolean
    default: true


runs:
  using: composite
  steps:
    - name: Get test file
      run: cp "${GITHUB_WORKSPACE}/.github/${{ inputs.test-file }}" /tmp
      shell: bash

    - name: Checkout to playground
      uses: actions/checkout@v2
      with:
        repository: "${{ inputs.vrtp }}"
        fetch-depth: 0

    - name: Configure git
      run: |
        git config --global user.email ${{ inputs.git-email }}
        git config --global user.name ${{ inputs.git-name }}
      shell: bash

    - name: Download compiled artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: vrelease-${{ github.sha }}-${{ inputs.artifact }}
        workflow: build-many.yml
      if: ${{ inputs.retrieve-artifact == 'true' }}

    - name: Prepare artifact
      run: |
        mv vrelease-*-${{ inputs.artifact }} vrelease
        chmod +x vrelease
      shell: bash
      if: ${{ inputs.retrieve-artifact == 'true' }}

    - name: Download committer
      run: curl -L -O "${{ inputs.committer }}-${{ inputs.artifact }}"
      shell: bash

    - name: Prepare committer
      run: |
        mv committer-${{ inputs.artifact }} committer
        chmod +x committer
      shell: bash

    - name: Run tests
      run: |
        ls -lash
        cp "/tmp/${{ inputs.test-file }}" ./test.sh
        bash test.sh
      shell: bash
      env:
        VRELEASE_AUTH_TOKEN: ${{ inputs.github-token }}

    - name: Checkout (back) to vrelease
      uses: actions/checkout@v2
